// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/BaseHeader.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    'IRi:fileTextLine': typeof import('~icons/ri/file-text-line')['default']
    IRiArrowRightLine: typeof import('~icons/ri/arrow-right-line')['default']
    IRiFileTextLine: typeof import('~icons/ri/file-text-line')['default']
    IRiImageLine: typeof import('~icons/ri/image-line')['default']
  }
}

export { }
